# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ECHG.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 310)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exe_path = QtWidgets.QTextBrowser(self.centralwidget)
        self.exe_path.setGeometry(QtCore.QRect(0, 30, 441, 31))
        self.exe_path.setObjectName("exe_path")
        self.Select_exe = QtWidgets.QPushButton(self.centralwidget)
        self.Select_exe.setGeometry(QtCore.QRect(440, 30, 51, 31))
        self.Select_exe.setObjectName("Select_exe")
        self.Select_dossier = QtWidgets.QPushButton(self.centralwidget)
        self.Select_dossier.setGeometry(QtCore.QRect(440, 80, 51, 31))
        self.Select_dossier.setObjectName("Select_dossier")
        self.Select_ECHG = QtWidgets.QPushButton(self.centralwidget)
        self.Select_ECHG.setGeometry(QtCore.QRect(440, 130, 51, 31))
        self.Select_ECHG.setObjectName("Select_ECHG")
        self.Select_PATO = QtWidgets.QPushButton(self.centralwidget)
        self.Select_PATO.setGeometry(QtCore.QRect(440, 180, 51, 31))
        self.Select_PATO.setObjectName("Select_PATO")
        self.Select_Atom = QtWidgets.QPushButton(self.centralwidget)
        self.Select_Atom.setGeometry(QtCore.QRect(440, 230, 51, 31))
        self.Select_Atom.setObjectName("Select_Atom")
        self.Dossier_path = QtWidgets.QTextEdit(self.centralwidget)
        self.Dossier_path.setGeometry(QtCore.QRect(0, 80, 441, 31))
        self.Dossier_path.setObjectName("Dossier_path")
        self.ECHG_path = QtWidgets.QTextEdit(self.centralwidget)
        self.ECHG_path.setGeometry(QtCore.QRect(0, 130, 441, 31))
        self.ECHG_path.setObjectName("ECHG_path")
        self.PATO_path = QtWidgets.QTextEdit(self.centralwidget)
        self.PATO_path.setGeometry(QtCore.QRect(0, 180, 441, 31))
        self.PATO_path.setObjectName("PATO_path")
        self.Atom_path = QtWidgets.QTextEdit(self.centralwidget)
        self.Atom_path.setGeometry(QtCore.QRect(0, 230, 441, 31))
        self.Atom_path.setObjectName("Atom_path")
        self.Contour_group = QtWidgets.QGroupBox(self.centralwidget)
        self.Contour_group.setGeometry(QtCore.QRect(500, 10, 241, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Contour_group.setFont(font)
        self.Contour_group.setObjectName("Contour_group")
        self.user_define = QtWidgets.QRadioButton(self.Contour_group)
        self.user_define.setEnabled(True)
        self.user_define.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.user_define.setAutoFillBackground(False)
        self.user_define.setChecked(True)
        self.user_define.setAutoRepeat(False)
        self.user_define.setObjectName("user_define")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.user_define)
        self.Bader = QtWidgets.QRadioButton(self.Contour_group)
        self.Bader.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.Bader.setObjectName("Bader")
        self.buttonGroup.addButton(self.Bader)
        self.User_val = QtWidgets.QTextEdit(self.Contour_group)
        self.User_val.setGeometry(QtCore.QRect(140, 20, 91, 31))
        self.User_val.setObjectName("User_val")
        self.Bader_val = QtWidgets.QTextEdit(self.Contour_group)
        self.Bader_val.setGeometry(QtCore.QRect(140, 70, 91, 31))
        self.Bader_val.setObjectName("Bader_val")
        self.Type_group = QtWidgets.QGroupBox(self.centralwidget)
        self.Type_group.setGeometry(QtCore.QRect(750, 10, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Type_group.setFont(font)
        self.Type_group.setObjectName("Type_group")
        self.widget = QtWidgets.QWidget(self.Type_group)
        self.widget.setGeometry(QtCore.QRect(11, 21, 113, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Defo = QtWidgets.QRadioButton(self.widget)
        self.Defo.setChecked(True)
        self.Defo.setObjectName("Defo")
        self.verticalLayout_2.addWidget(self.Defo)
        self.Spin = QtWidgets.QRadioButton(self.widget)
        self.Spin.setObjectName("Spin")
        self.verticalLayout_2.addWidget(self.Spin)
        self.Up = QtWidgets.QRadioButton(self.widget)
        self.Up.setObjectName("Up")
        self.verticalLayout_2.addWidget(self.Up)
        self.Down = QtWidgets.QRadioButton(self.widget)
        self.Down.setObjectName("Down")
        self.verticalLayout_2.addWidget(self.Down)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 210, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(890, 10, 201, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.H_bond = QtWidgets.QTextEdit(self.groupBox)
        self.H_bond.setGeometry(QtCore.QRect(120, 50, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.H_bond.setFont(font)
        self.H_bond.setObjectName("H_bond")
        self.Line_width = QtWidgets.QTextEdit(self.groupBox)
        self.Line_width.setGeometry(QtCore.QRect(120, 20, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Line_width.setFont(font)
        self.Line_width.setObjectName("Line_width")
        self.Bond = QtWidgets.QTextEdit(self.groupBox)
        self.Bond.setGeometry(QtCore.QRect(120, 80, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Bond.setFont(font)
        self.Bond.setObjectName("Bond")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(500, 120, 591, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(70, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setObjectName("label_12")
        self.left2right = QtWidgets.QCheckBox(self.groupBox_2)
        self.left2right.setGeometry(QtCore.QRect(90, 120, 103, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.left2right.setFont(font)
        self.left2right.setObjectName("left2right")
        self.up2down = QtWidgets.QCheckBox(self.groupBox_2)
        self.up2down.setGeometry(QtCore.QRect(10, 120, 103, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.up2down.setFont(font)
        self.up2down.setObjectName("up2down")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(70, 60, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(180, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_14.setFont(font)
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(180, 60, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(280, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_16.setFont(font)
        self.label_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_16.setObjectName("label_16")
        self.widget1 = QtWidgets.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(277, 70, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget1.setFont(font)
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_17 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_17.setFont(font)
        self.label_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.pos_color = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pos_color.setFont(font)
        self.pos_color.setObjectName("pos_color")
        self.pos_color.addItem("")
        self.pos_color.addItem("")
        self.pos_color.addItem("")
        self.pos_color.addItem("")
        self.pos_color.addItem("")
        self.pos_color.addItem("")
        self.pos_color.addItem("")
        self.pos_color.addItem("")
        self.gridLayout_2.addWidget(self.pos_color, 0, 1, 1, 1)
        self.pos_line = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pos_line.setFont(font)
        self.pos_line.setObjectName("pos_line")
        self.pos_line.addItem("")
        self.pos_line.addItem("")
        self.pos_line.addItem("")
        self.pos_line.addItem("")
        self.gridLayout_2.addWidget(self.pos_line, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 0, 1, 1)
        self.neg_color = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.neg_color.setFont(font)
        self.neg_color.setObjectName("neg_color")
        self.neg_color.addItem("")
        self.neg_color.addItem("")
        self.neg_color.addItem("")
        self.neg_color.addItem("")
        self.neg_color.addItem("")
        self.neg_color.addItem("")
        self.neg_color.addItem("")
        self.neg_color.addItem("")
        self.gridLayout_2.addWidget(self.neg_color, 1, 1, 1, 1)
        self.neg_line = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.neg_line.setFont(font)
        self.neg_line.setObjectName("neg_line")
        self.neg_line.addItem("")
        self.neg_line.addItem("")
        self.neg_line.addItem("")
        self.neg_line.addItem("")
        self.gridLayout_2.addWidget(self.neg_line, 1, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.neu_color = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.neu_color.setFont(font)
        self.neu_color.setObjectName("neu_color")
        self.neu_color.addItem("")
        self.neu_color.addItem("")
        self.neu_color.addItem("")
        self.neu_color.addItem("")
        self.neu_color.addItem("")
        self.neu_color.addItem("")
        self.neu_color.addItem("")
        self.neu_color.addItem("")
        self.gridLayout_2.addWidget(self.neu_color, 2, 1, 1, 1)
        self.neu_line = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.neu_line.setFont(font)
        self.neu_line.setObjectName("neu_line")
        self.neu_line.addItem("")
        self.neu_line.addItem("")
        self.neu_line.addItem("")
        self.neu_line.addItem("")
        self.gridLayout_2.addWidget(self.neu_line, 2, 2, 1, 1)
        self.contour_width = QtWidgets.QTextEdit(self.groupBox_2)
        self.contour_width.setGeometry(QtCore.QRect(80, 30, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contour_width.setFont(font)
        self.contour_width.setObjectName("contour_width")
        self.fontsize = QtWidgets.QTextEdit(self.groupBox_2)
        self.fontsize.setGeometry(QtCore.QRect(180, 30, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fontsize.setFont(font)
        self.fontsize.setObjectName("fontsize")
        self.axiesize = QtWidgets.QTextEdit(self.groupBox_2)
        self.axiesize.setGeometry(QtCore.QRect(280, 30, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.axiesize.setFont(font)
        self.axiesize.setObjectName("axiesize")
        self.resolution = QtWidgets.QTextEdit(self.groupBox_2)
        self.resolution.setGeometry(QtCore.QRect(80, 80, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resolution.setFont(font)
        self.resolution.setObjectName("resolution")
        self.plan_dis = QtWidgets.QTextEdit(self.groupBox_2)
        self.plan_dis.setGeometry(QtCore.QRect(180, 80, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plan_dis.setFont(font)
        self.plan_dis.setObjectName("plan_dis")
        self.widget2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 51, 91))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.png = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.png.setFont(font)
        self.png.setChecked(True)
        self.png.setObjectName("png")
        self.verticalLayout.addWidget(self.png)
        self.ps = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ps.setFont(font)
        self.ps.setChecked(False)
        self.ps.setObjectName("ps")
        self.verticalLayout.addWidget(self.ps)
        self.eps = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eps.setFont(font)
        self.eps.setObjectName("eps")
        self.verticalLayout.addWidget(self.eps)
        self.pdf = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pdf.setFont(font)
        self.pdf.setObjectName("pdf")
        self.verticalLayout.addWidget(self.pdf)
        self.widget3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget3.setGeometry(QtCore.QRect(380, 14, 208, 51))
        self.widget3.setObjectName("widget3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.notitle = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.notitle.setFont(font)
        self.notitle.setObjectName("notitle")
        self.gridLayout.addWidget(self.notitle, 0, 1, 1, 1)
        self.xyticks = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.xyticks.setFont(font)
        self.xyticks.setChecked(True)
        self.xyticks.setObjectName("xyticks")
        self.gridLayout.addWidget(self.xyticks, 0, 0, 1, 1)
        self.noatoms = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.noatoms.setFont(font)
        self.noatoms.setObjectName("noatoms")
        self.gridLayout.addWidget(self.noatoms, 1, 1, 1, 1)
        self.boxwhite = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boxwhite.setFont(font)
        self.boxwhite.setObjectName("boxwhite")
        self.gridLayout.addWidget(self.boxwhite, 1, 0, 1, 1)
        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(1030, 260, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Run.setFont(font)
        self.Run.setObjectName("Run")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pos_color.setCurrentIndex(2)
        self.pos_line.setCurrentIndex(0)
        self.neg_line.setCurrentIndex(1)
        self.neu_color.setCurrentIndex(1)
        self.neu_line.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exe_path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Select_exe.setText(_translate("MainWindow", "Select"))
        self.Select_dossier.setText(_translate("MainWindow", "Select"))
        self.Select_ECHG.setText(_translate("MainWindow", "Select"))
        self.Select_PATO.setText(_translate("MainWindow", "Select"))
        self.Select_Atom.setText(_translate("MainWindow", "Select"))
        self.Dossier_path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ECHG_path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.PATO_path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Atom_path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Contour_group.setTitle(_translate("MainWindow", "Contour Interval"))
        self.user_define.setText(_translate("MainWindow", "User define"))
        self.Bader.setText(_translate("MainWindow", "Bader"))
        self.User_val.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">0.05</span></p></body></html>"))
        self.Bader_val.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">0.01</span></p></body></html>"))
        self.Type_group.setTitle(_translate("MainWindow", "Type Affiage"))
        self.Defo.setText(_translate("MainWindow", "Deformation"))
        self.Spin.setText(_translate("MainWindow", "Spin"))
        self.Up.setText(_translate("MainWindow", "Up"))
        self.Down.setText(_translate("MainWindow", "Down"))
        self.label.setText(_translate("MainWindow", "ECHG.exe:"))
        self.label_2.setText(_translate("MainWindow", "Dossier:"))
        self.label_3.setText(_translate("MainWindow", "ECHG file:"))
        self.label_4.setText(_translate("MainWindow", "PATO file:"))
        self.label_5.setText(_translate("MainWindow", "Atom list file:"))
        self.groupBox.setTitle(_translate("MainWindow", "Bond"))
        self.label_6.setText(_translate("MainWindow", "Line Width:"))
        self.label_7.setText(_translate("MainWindow", "H bond length:"))
        self.label_8.setText(_translate("MainWindow", "Bond length:"))
        self.H_bond.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">1.2</span></p></body></html>"))
        self.Line_width.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">1</span></p></body></html>"))
        self.Bond.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">2.0</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Image"))
        self.label_12.setText(_translate("MainWindow", "Contour width:"))
        self.left2right.setText(_translate("MainWindow", "left2right"))
        self.up2down.setText(_translate("MainWindow", "up2down"))
        self.label_13.setText(_translate("MainWindow", "Resolution:"))
        self.label_14.setText(_translate("MainWindow", "FontSize:"))
        self.label_15.setText(_translate("MainWindow", "Plan Distance:"))
        self.label_16.setText(_translate("MainWindow", "Axie Size:"))
        self.label_17.setText(_translate("MainWindow", "Positive"))
        self.pos_color.setItemText(0, _translate("MainWindow", "Red"))
        self.pos_color.setItemText(1, _translate("MainWindow", "Green"))
        self.pos_color.setItemText(2, _translate("MainWindow", "Blue"))
        self.pos_color.setItemText(3, _translate("MainWindow", "Cyan"))
        self.pos_color.setItemText(4, _translate("MainWindow", "Magenta"))
        self.pos_color.setItemText(5, _translate("MainWindow", "Yellow"))
        self.pos_color.setItemText(6, _translate("MainWindow", "Black"))
        self.pos_color.setItemText(7, _translate("MainWindow", "White"))
        self.pos_line.setItemText(0, _translate("MainWindow", "solid \'-\'"))
        self.pos_line.setItemText(1, _translate("MainWindow", "dashed \'--\'"))
        self.pos_line.setItemText(2, _translate("MainWindow", "dotted line \'.\'"))
        self.pos_line.setItemText(3, _translate("MainWindow", "dashdot \'-.\'"))
        self.label_18.setText(_translate("MainWindow", "Negative"))
        self.neg_color.setItemText(0, _translate("MainWindow", "Red"))
        self.neg_color.setItemText(1, _translate("MainWindow", "Green"))
        self.neg_color.setItemText(2, _translate("MainWindow", "Blue"))
        self.neg_color.setItemText(3, _translate("MainWindow", "Cyan"))
        self.neg_color.setItemText(4, _translate("MainWindow", "Magenta"))
        self.neg_color.setItemText(5, _translate("MainWindow", "Yellow"))
        self.neg_color.setItemText(6, _translate("MainWindow", "Black"))
        self.neg_color.setItemText(7, _translate("MainWindow", "White"))
        self.neg_line.setItemText(0, _translate("MainWindow", "solid \'-\'"))
        self.neg_line.setItemText(1, _translate("MainWindow", "dashed \'--\'"))
        self.neg_line.setItemText(2, _translate("MainWindow", "dotted \'.\'"))
        self.neg_line.setItemText(3, _translate("MainWindow", "dashdot \'-.\'"))
        self.label_19.setText(_translate("MainWindow", "Neutral"))
        self.neu_color.setItemText(0, _translate("MainWindow", "Red"))
        self.neu_color.setItemText(1, _translate("MainWindow", "Green"))
        self.neu_color.setItemText(2, _translate("MainWindow", "Blue"))
        self.neu_color.setItemText(3, _translate("MainWindow", "Cyan"))
        self.neu_color.setItemText(4, _translate("MainWindow", "Magenta"))
        self.neu_color.setItemText(5, _translate("MainWindow", "Yellow"))
        self.neu_color.setItemText(6, _translate("MainWindow", "Black"))
        self.neu_color.setItemText(7, _translate("MainWindow", "White"))
        self.neu_line.setItemText(0, _translate("MainWindow", "solid \'-\'"))
        self.neu_line.setItemText(1, _translate("MainWindow", "dashed \'--\'"))
        self.neu_line.setItemText(2, _translate("MainWindow", "dotted \'.\'"))
        self.neu_line.setItemText(3, _translate("MainWindow", "dashdot \'-.\'"))
        self.contour_width.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">1</span></p></body></html>"))
        self.fontsize.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">12</span></p></body></html>"))
        self.axiesize.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">18</span></p></body></html>"))
        self.resolution.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">400</span></p></body></html>"))
        self.plan_dis.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">0.3</span></p></body></html>"))
        self.png.setText(_translate("MainWindow", "png"))
        self.ps.setText(_translate("MainWindow", "ps"))
        self.eps.setText(_translate("MainWindow", "eps"))
        self.pdf.setText(_translate("MainWindow", "pdf"))
        self.notitle.setText(_translate("MainWindow", "No title"))
        self.xyticks.setText(_translate("MainWindow", "XY ticks"))
        self.noatoms.setText(_translate("MainWindow", "No atoms"))
        self.boxwhite.setText(_translate("MainWindow", "Box white"))
        self.Run.setText(_translate("MainWindow", "RUN"))

